// The emoji the picker offers: common ones, with the words its search
// matches. Any other emoji can be typed or pasted; this list only saves the
// trip to the system's emoji keyboard.

export type EmojiChoice = { emoji: string; words: string }
export type EmojiCategory = { label: string; emoji: EmojiChoice[] }

// "🚀 rocket launch" reads better in a list this long than an object would.
const parse = (lines: string[]): EmojiChoice[] =>
  lines.map((line) => {
    const [emoji, ...words] = line.split(" ")
    return { emoji, words: words.join(" ") }
  })

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    label: "Status",
    emoji: parse([
      "✅ check done yes complete",
      "❌ cross no failed wrong",
      "⚠️ warning caution risk",
      "🚧 construction work in progress wip",
      "🚫 forbidden blocked no entry",
      "⛔ stop no entry blocked",
      "❓ question unknown",
      "❗ exclamation important",
      "💡 idea lightbulb",
      "🔥 fire hot urgent",
      "⭐ star favorite",
      "✨ sparkles new shiny",
      "🎯 target goal bullseye",
      "🏁 finish flag done",
      "🚩 red flag risk",
      "📌 pin pinned",
      "🔴 red circle",
      "🟠 orange circle",
      "🟡 yellow circle",
      "🟢 green circle",
      "🔵 blue circle",
      "🟣 purple circle",
      "⚫ black circle",
      "⚪ white circle",
      "🆕 new",
      "🆗 ok",
      "🔜 soon",
      "💤 sleep idle paused",
      "♻️ recycle reuse",
      "🐛 bug defect",
      "💥 boom crash explosion",
      "🧊 ice frozen freeze",
    ]),
  },
  {
    label: "Work",
    emoji: parse([
      "🚀 rocket launch ship deploy",
      "📦 package box parcel",
      "🧩 puzzle piece plugin",
      "🛠️ tools build fix",
      "🔧 wrench fix tool",
      "🔨 hammer build",
      "⚙️ gear settings",
      "🧪 test tube experiment",
      "🔬 microscope research",
      "🔭 telescope vision explore",
      "📝 memo note write",
      "📄 page document",
      "📃 page curl document",
      "📚 books docs library",
      "📖 open book read",
      "📋 clipboard checklist",
      "📁 folder",
      "🗂️ dividers index files",
      "🗃️ card file box archive",
      "🗄️ file cabinet storage",
      "🗑️ trash bin delete",
      "📅 calendar date",
      "🗓️ calendar spiral plan",
      "⏰ alarm clock time",
      "⏱️ stopwatch timer",
      "⏳ hourglass waiting",
      "📈 chart up growth",
      "📉 chart down decline",
      "📊 bar chart metrics",
      "🧮 abacus calculate",
      "🧭 compass direction",
      "🗺️ map roadmap",
      "🏗️ building construction",
      "🧱 brick wall firewall",
    ]),
  },
  {
    label: "Tech",
    emoji: parse([
      "💻 laptop computer",
      "🖥️ desktop computer monitor",
      "📱 phone mobile",
      "⌨️ keyboard",
      "🖱️ mouse",
      "🖨️ printer",
      "💾 floppy disk save storage",
      "💿 disc cd",
      "🔌 plug power connector",
      "🔋 battery",
      "📡 satellite antenna signal",
      "🌐 globe web internet",
      "☁️ cloud",
      "⚡ zap lightning fast function",
      "🤖 robot bot ai",
      "🧠 brain ai model",
      "👾 alien game monster",
      "🔗 link chain url",
      "🔍 search magnifier find",
      "🔎 search magnifier right",
      "📶 signal bars network",
      "🛰️ satellite",
      "🕸️ web spider network",
      "🧵 thread",
      "🪝 hook webhook",
      "🧲 magnet attract",
      "🎛️ control knobs",
      "📟 pager alert oncall",
    ]),
  },
  {
    label: "Security",
    emoji: parse([
      "🔒 lock locked secure",
      "🔓 unlock open",
      "🔐 lock key secure",
      "🔑 key secret",
      "🗝️ old key",
      "🛡️ shield protect",
      "👁️ eye watch",
      "🕵️ detective spy audit",
      "🚨 siren alert incident",
      "🪪 id card identity",
      "🧾 receipt audit log",
    ]),
  },
  {
    label: "Messages",
    emoji: parse([
      "✉️ envelope mail email",
      "📧 email",
      "📨 incoming mail",
      "📤 outbox send",
      "📥 inbox receive",
      "📬 mailbox",
      "💬 speech chat message",
      "🗨️ speech bubble comment",
      "📣 megaphone announce",
      "📢 loudspeaker broadcast",
      "🔔 bell notification",
      "🔕 bell off muted",
      "📞 phone call",
      "☎️ telephone",
    ]),
  },
  {
    label: "People",
    emoji: parse([
      "👤 user person silhouette",
      "👥 users people team",
      "🧑‍💻 developer technologist coder",
      "🧑‍💼 office worker business",
      "🧑‍🔬 scientist",
      "🧑‍🎨 artist designer",
      "🧑‍🏫 teacher",
      "🙋 raising hand question",
      "🤝 handshake deal partner",
      "👍 thumbs up yes approve",
      "👎 thumbs down no reject",
      "👏 clap applause",
      "🙏 thanks please pray",
      "👀 eyes look review",
      "🎉 party celebrate tada",
      "❤️ heart love",
      "😀 smile happy",
      "🤔 thinking hmm",
      "😅 sweat nervous",
      "😴 sleeping",
      "😱 scream shock",
      "🥳 party face celebrate",
    ]),
  },
  {
    label: "Money and places",
    emoji: parse([
      "💰 money bag",
      "💵 dollar cash",
      "💳 credit card payment",
      "🪙 coin",
      "🏦 bank",
      "🛒 cart shopping",
      "🛍️ shopping bags",
      "🏷️ tag label price",
      "🎁 gift present",
      "🏪 store shop",
      "🏢 office building company",
      "🏭 factory",
      "🏠 house home",
      "🏥 hospital",
      "🏫 school",
      "🚚 truck delivery",
      "✈️ plane flight",
      "🚢 ship",
      "🚗 car",
      "📍 pin location",
      "🌍 earth europe africa world",
      "🌎 earth americas world",
      "🌏 earth asia world",
    ]),
  },
  {
    label: "Nature and things",
    emoji: parse([
      "🌱 seedling grow new",
      "🌳 tree",
      "🍀 clover luck",
      "🌊 wave water stream",
      "☀️ sun",
      "🌙 moon night",
      "❄️ snowflake cold",
      "🌈 rainbow",
      "🐳 whale docker",
      "🐘 elephant postgres php",
      "🐍 snake python",
      "🦀 crab rust",
      "🐹 hamster gopher go",
      "☕ coffee java",
      "💎 gem ruby",
      "🐙 octopus github",
      "🦊 fox gitlab firefox",
      "🐧 penguin linux",
      "🍎 apple",
      "🎨 palette art design",
      "🎬 clapper video",
      "🎵 music note",
      "📷 camera photo",
      "🎮 game controller",
      "🏆 trophy win",
      "🥇 gold medal first",
      "🔮 crystal ball predict",
      "🧹 broom cleanup",
    ]),
  },
]
